### ISSUE TITLE
USB Booting Support?

### ISSUE THREAD

**Issue by WinsDominoes** [davidgiven/minix2#3]
Hello!

I am interested in MINIX and I was wondering if you could use the combo to boot MINIX from a USB Stick? 

Win

**Comment by davidgiven** [comment]
I'm not sure, TBH. Minix 2 has no USB stack so it couldn't talk natively to a USB device but it might be possible to use BIOS FDD emulation to make it work. You'll have to try it; although it's possible that you'll only be able to load the kernel but not mount the root filesystem.

**Comment by WinsDominoes** [comment]
Hmm, alright then. Thanks!
